# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - manders

on:
  push:
    branches:
      - azure
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Create and start virtual environment
        run: |
          python -m venv backmande
          source backmande/bin/activate

      - name: Install dependencies
        run: |
          pip install -r pbackmande/requirements.txt
          ls -R

          - name: Zip artifact for deployment
          run: zip -r release.zip backmande pbackmande
  
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with: 
          name: python-app
          path: release.zip

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

#      - name: Migrate database
#        run: python pbackmande/manage.py makemigrations
#      - name: Migrate database
#        run: python pbackmande/manage.py migrate

#      - name: Start Django development server
#        run: python pbackmande/manage.py runserver

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip -o release.zip

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "manders"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9096D99FC0684EF9A9DB02CD43C3A88F }}
